// <auto-generated />
using System;
using API_Dinamis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PokemonReviewApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240604043326_actiondetailEmployee")]
    partial class actiondetailEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API_Dinamis.Models.Authx", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Auths");
                });

            modelBuilder.Entity("API_Dinamis.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZipCodeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ZipCodeId");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("API_Dinamis.Models.BranchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("BranchTempId")
                        .HasColumnType("integer");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZipCodeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BranchLog");
                });

            modelBuilder.Entity("API_Dinamis.Models.BranchLogTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZipCodeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BranchLogTemp");
                });

            modelBuilder.Entity("API_Dinamis.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("API_Dinamis.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address2")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Fax")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KseiCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Npwp")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NpwpDate")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("SinvestMiCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SinvestSaCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZipCodeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CompanyCode")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.HasIndex("ZipCodeId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("API_Dinamis.Models.CompanyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address2")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CompanyTempId")
                        .HasColumnType("integer");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Fax")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KseiCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Npwp")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NpwpDate")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("SinvestMiCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SinvestSaCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZipCodeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CompanyLog");
                });

            modelBuilder.Entity("API_Dinamis.Models.CompanyLogTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address2")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Fax")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KseiCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Npwp")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NpwpDate")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("SinvestMiCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SinvestSaCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZipCodeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode")
                        .IsUnique();

                    b.ToTable("CompanyLogTemp");
                });

            modelBuilder.Entity("API_Dinamis.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("API_Dinamis.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("API_Dinamis.Models.DepartmentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DepartmentTempId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DepartmentLog");
                });

            modelBuilder.Entity("API_Dinamis.Models.DepartmentLogTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DepartmentLogTemp");
                });

            modelBuilder.Entity("API_Dinamis.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<int>("AllowSaveToExcel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BLWAPERDLicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("BLWAPERDLicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("BLWMILicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("BLWMILicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("BLWPEELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("BLWPEELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("BLWPPELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("BLWPPELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("HasBLWAPERDLicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasBLWMILicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasBLWPEELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasBLWPPELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMIPPEELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMIPWMILicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMPILicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMWAPERDLicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMWMILicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMWPEELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMWPPELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPPLWAPERDLicense")
                        .HasColumnType("integer");

                    b.Property<string>("HomeAddress1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HomeAddress2")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("HomeCityId")
                        .HasColumnType("integer");

                    b.Property<int>("HomeZipCodeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IDExpiredDate")
                        .HasColumnType("date");

                    b.Property<string>("IDNo")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<int>("IDType")
                        .HasColumnType("integer");

                    b.Property<string>("Initial")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<string>("MailAddress1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MailAddress2")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MailCityId")
                        .HasColumnType("integer");

                    b.Property<int>("MailZipCodeId")
                        .HasColumnType("integer");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("integer");

                    b.Property<int>("MarketingPosition")
                        .HasColumnType("integer");

                    b.Property<string>("NPWP")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Nationality")
                        .HasColumnType("integer");

                    b.Property<string>("OtherEmail")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("PMIPPEELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMIPPEELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMIPWMILicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMIPWMILicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMPILicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMPILicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMWAPERDLicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMWAPERDLicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMWMILicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMWMILicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMWPEELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMWPEELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMWPPELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMWPPELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PPLWAPERDLicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PPLWAPERDLicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<int>("PresDirectorXN1Signer")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ResignDate")
                        .HasColumnType("date");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("WARPERDStatus")
                        .HasColumnType("integer");

                    b.Property<int>("WARPERDType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("API_Dinamis.Models.EmployeeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<int>("LicenseId")
                        .HasColumnType("integer");

                    b.Property<string>("LicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LicenseId");

                    b.ToTable("EmployeeDetail");
                });

            modelBuilder.Entity("API_Dinamis.Models.EmployeeDetailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionRemarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeDetailId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeDetailTempId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeTempId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<int>("LicenseId")
                        .HasColumnType("integer");

                    b.Property<string>("LicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmployeeDetailLog");
                });

            modelBuilder.Entity("API_Dinamis.Models.EmployeeDetailLogTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionRemarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeDetailId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeTempId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<int>("LicenseId")
                        .HasColumnType("integer");

                    b.Property<string>("LicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmployeeDetailLogTemp");
                });

            modelBuilder.Entity("API_Dinamis.Models.EmployeeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("AllowSaveToExcel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BLWAPERDLicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("BLWAPERDLicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("BLWMILicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("BLWMILicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("BLWPEELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("BLWPEELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("BLWPPELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("BLWPPELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeTempId")
                        .HasColumnType("integer");

                    b.Property<int>("HasBLWAPERDLicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasBLWMILicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasBLWPEELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasBLWPPELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMIPPEELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMIPWMILicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMPILicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMWAPERDLicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMWMILicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMWPEELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMWPPELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPPLWAPERDLicense")
                        .HasColumnType("integer");

                    b.Property<string>("HomeAddress1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HomeAddress2")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("HomeCityId")
                        .HasColumnType("integer");

                    b.Property<int>("HomeZipCodeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IDExpiredDate")
                        .HasColumnType("date");

                    b.Property<string>("IDNo")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<int>("IDType")
                        .HasColumnType("integer");

                    b.Property<string>("Initial")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<string>("MailAddress1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MailAddress2")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MailCityId")
                        .HasColumnType("integer");

                    b.Property<int>("MailZipCodeId")
                        .HasColumnType("integer");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("integer");

                    b.Property<int>("MarketingPosition")
                        .HasColumnType("integer");

                    b.Property<string>("NPWP")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Nationality")
                        .HasColumnType("integer");

                    b.Property<string>("OtherEmail")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("PMIPPEELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMIPPEELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMIPWMILicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMIPWMILicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMPILicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMPILicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMWAPERDLicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMWAPERDLicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMWMILicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMWMILicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMWPEELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMWPEELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMWPPELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMWPPELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PPLWAPERDLicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PPLWAPERDLicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<int>("PresDirectorXN1Signer")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ResignDate")
                        .HasColumnType("date");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("WARPERDStatus")
                        .HasColumnType("integer");

                    b.Property<int>("WARPERDType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EmployeeLog");
                });

            modelBuilder.Entity("API_Dinamis.Models.EmployeeLogTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("AllowSaveToExcel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BLWAPERDLicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("BLWAPERDLicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("BLWMILicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("BLWMILicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("BLWPEELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("BLWPEELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("BLWPPELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("BLWPPELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("HasBLWAPERDLicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasBLWMILicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasBLWPEELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasBLWPPELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMIPPEELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMIPWMILicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMPILicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMWAPERDLicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMWMILicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMWPEELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPMWPPELicense")
                        .HasColumnType("integer");

                    b.Property<int>("HasPPLWAPERDLicense")
                        .HasColumnType("integer");

                    b.Property<string>("HomeAddress1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HomeAddress2")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("HomeCityId")
                        .HasColumnType("integer");

                    b.Property<int>("HomeZipCodeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IDExpiredDate")
                        .HasColumnType("date");

                    b.Property<string>("IDNo")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<int>("IDType")
                        .HasColumnType("integer");

                    b.Property<string>("Initial")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<string>("MailAddress1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MailAddress2")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MailCityId")
                        .HasColumnType("integer");

                    b.Property<int>("MailZipCodeId")
                        .HasColumnType("integer");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("integer");

                    b.Property<int>("MarketingPosition")
                        .HasColumnType("integer");

                    b.Property<string>("NPWP")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Nationality")
                        .HasColumnType("integer");

                    b.Property<string>("OtherEmail")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("PMIPPEELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMIPPEELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMIPWMILicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMIPWMILicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMPILicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMPILicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMWAPERDLicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMWAPERDLicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMWMILicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMWMILicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMWPEELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMWPEELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PMWPPELicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PMWPPELicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PPLWAPERDLicenseIssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("PPLWAPERDLicenseNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<int>("PresDirectorXN1Signer")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ResignDate")
                        .HasColumnType("date");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("WARPERDStatus")
                        .HasColumnType("integer");

                    b.Property<int>("WARPERDType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EmployeeLogTemp");
                });

            modelBuilder.Entity("API_Dinamis.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(125)");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HolidayDate")
                        .IsUnique();

                    b.ToTable("Holiday");
                });

            modelBuilder.Entity("API_Dinamis.Models.HolidayLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(125)");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("date");

                    b.Property<int>("HolidayId")
                        .HasColumnType("integer");

                    b.Property<int>("HolidayTempId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HolidayLog");
                });

            modelBuilder.Entity("API_Dinamis.Models.HolidayLogTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(125)");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("date");

                    b.Property<int>("HolidayId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HolidayDate")
                        .IsUnique();

                    b.ToTable("HolidayLogTemp");
                });

            modelBuilder.Entity("API_Dinamis.Models.Key", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Keys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Key");
                });

            modelBuilder.Entity("API_Dinamis.Models.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<string>("LicenseCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("License");
                });

            modelBuilder.Entity("API_Dinamis.Models.LicenseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<string>("LicenseCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("LicenseId")
                        .HasColumnType("integer");

                    b.Property<int>("LicenseTempId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LicenseLog");
                });

            modelBuilder.Entity("API_Dinamis.Models.LicenseLogTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<string>("LicenseCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("LicenseId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LicenseLogTemp");
                });

            modelBuilder.Entity("API_Dinamis.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Add")
                        .HasColumnType("boolean");

                    b.Property<bool>("Delete")
                        .HasColumnType("boolean");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Update")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("API_Dinamis.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("API_Dinamis.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("API_Dinamis.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("API_Dinamis.Models.RoleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Add")
                        .HasColumnType("boolean");

                    b.Property<bool>("Delete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<bool>("Run")
                        .HasColumnType("boolean");

                    b.Property<bool>("Update")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleDetail");
                });

            modelBuilder.Entity("API_Dinamis.Models.RoleDetailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionRemarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Add")
                        .HasColumnType("boolean");

                    b.Property<bool>("Delete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleDetailId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleDetailTempId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleTempId")
                        .HasColumnType("integer");

                    b.Property<bool>("Run")
                        .HasColumnType("boolean");

                    b.Property<bool>("Update")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RoleDetailLog");
                });

            modelBuilder.Entity("API_Dinamis.Models.RoleDetailLogTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionRemarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Add")
                        .HasColumnType("boolean");

                    b.Property<bool>("Delete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleDetailId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleTempId")
                        .HasColumnType("integer");

                    b.Property<bool>("Run")
                        .HasColumnType("boolean");

                    b.Property<bool>("Update")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RoleDetailLogTemp");
                });

            modelBuilder.Entity("API_Dinamis.Models.RoleLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleTempId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RoleLog");
                });

            modelBuilder.Entity("API_Dinamis.Models.RoleLogTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("date");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RoleLogTemp");
                });

            modelBuilder.Entity("API_Dinamis.Models.StandardValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("DataName")
                        .IsRequired()
                        .HasColumnType("varchar(125)");

                    b.Property<string>("DataValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("ValueInPercentage")
                        .HasColumnType("boolean");

                    b.Property<string>("ValueOption")
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("DataName")
                        .IsUnique();

                    b.ToTable("StandardValue");
                });

            modelBuilder.Entity("API_Dinamis.Models.StandardValueLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .HasColumnType("text");

                    b.Property<int>("DataId")
                        .HasColumnType("integer");

                    b.Property<string>("DataName")
                        .IsRequired()
                        .HasColumnType("varchar(125)");

                    b.Property<int>("DataTempId")
                        .HasColumnType("integer");

                    b.Property<string>("DataValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("ValueInPercentage")
                        .HasColumnType("boolean");

                    b.Property<string>("ValueOption")
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("StandardValueLog");
                });

            modelBuilder.Entity("API_Dinamis.Models.StandardValueLogTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ActionRemarks")
                        .HasColumnType("text");

                    b.Property<int>("DataId")
                        .HasColumnType("integer");

                    b.Property<string>("DataName")
                        .IsRequired()
                        .HasColumnType("varchar(125)");

                    b.Property<string>("DataValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("ValueInPercentage")
                        .HasColumnType("boolean");

                    b.Property<string>("ValueOption")
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("DataName")
                        .IsUnique();

                    b.ToTable("StandardValueLogTemp");
                });

            modelBuilder.Entity("API_Dinamis.Models.Zipcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("ZipCode");
                });

            modelBuilder.Entity("API_Dinamis.Models.Branch", b =>
                {
                    b.HasOne("API_Dinamis.Models.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Dinamis.Models.Zipcode", null)
                        .WithMany()
                        .HasForeignKey("ZipCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Dinamis.Models.Company", b =>
                {
                    b.HasOne("API_Dinamis.Models.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Dinamis.Models.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Dinamis.Models.Zipcode", null)
                        .WithMany()
                        .HasForeignKey("ZipCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Dinamis.Models.Department", b =>
                {
                    b.HasOne("API_Dinamis.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Dinamis.Models.EmployeeDetail", b =>
                {
                    b.HasOne("API_Dinamis.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Dinamis.Models.License", null)
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Dinamis.Models.Menu", b =>
                {
                    b.HasOne("API_Dinamis.Models.Module", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Dinamis.Models.Role", b =>
                {
                    b.HasOne("API_Dinamis.Models.Module", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Dinamis.Models.RoleDetail", b =>
                {
                    b.HasOne("API_Dinamis.Models.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Dinamis.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Dinamis.Models.Zipcode", b =>
                {
                    b.HasOne("API_Dinamis.Models.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
